// Standalone seed script — requires Node 20+
// Usage: node scripts/seed.mjs
// Reads NEXT_PUBLIC_SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY from .env.local

import { readFileSync } from "fs";
import { resolve } from "path";

function loadEnv() {
  try {
    const raw = readFileSync(resolve(process.cwd(), ".env.local"), "utf8");
    for (const line of raw.split("\n")) {
      const [key, ...rest] = line.split("=");
      if (key && rest.length) process.env[key.trim()] = rest.join("=").trim();
    }
  } catch {}
}
loadEnv();

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL;
const SERVICE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;
if (!SUPABASE_URL || !SERVICE_KEY) {
  console.error("Missing NEXT_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY in .env.local");
  process.exit(1);
}

const headers = {
  apikey: SERVICE_KEY,
  Authorization: `Bearer ${SERVICE_KEY}`,
  "Content-Type": "application/json",
  Prefer: "resolution=merge-duplicates",
};

const now = new Date().toISOString();

let idCounter = 0;
function bid() { return `b-seed-${++idCounter}`; }

const IDS = [
  "a9fb3163-d448-49b0-9092-8b0f7d97fc0d",
  "85e2c4af-b5ef-4ee5-ae21-19dd5fbf2f50",
  "e715d03f-76c4-4bfa-b09b-51b6a534ec56",
  "01b65caf-671a-4cc2-98a6-69efb2b49b39",
  "89310543-9ff8-4e95-a0b3-9fa0bbcaac0e",
  "0ab6f4f3-ed5a-4f34-aeea-14ff763a2d2e",
  "8fbc4299-040f-455d-9d38-b49d9ce71f6c",
  "bf170575-ac9e-4348-9239-c6a1c0301e72",
  "9ccdeb97-eef0-4f12-b02d-5c5332f48566",
  "619a65f7-7df3-4722-847a-08878ad7b96a",
  "89b4de34-0f8a-46e3-a7b2-09b3d4762266",
  "a74cc082-74f2-4e3b-b753-94ee12e70a51",
  "54bda701-813d-4bf3-b93c-9251dbbdec04",
  "bca5f1ce-885a-4466-bf6c-4b7845dc8da2",
  "235492a0-21f9-4030-a2ee-1e5c3b1b48ca",
  "7b67989f-520f-4dd8-be83-d0879ed7ff21",
  "1a4f3c05-9bb8-4acc-b991-f979978da39f",
  "7b6162f0-00ab-40b6-9975-52c3199955ff",
];

const posts = [
  { id: IDS[0], slug: "palladio-hotel-buenos-aires-mayo-identidad-argentina", category: "Gastronomia", status: "published", cover_image: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=1200&q=80", featured: true, published_at: "2026-05-20T10:00:00.000Z", created_at: now, updated_at: now },
  { id: IDS[1], slug: "record-argentinos-japon-2025-destino-turismo", category: "Viajes", status: "published", cover_image: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?auto=format&fit=crop&w=1200&q=80", featured: true, published_at: "2026-05-20T09:00:00.000Z", created_at: now, updated_at: now },
  { id: IDS[2], slug: "calvin-klein-jung-kook-coleccion-capsula-2026", category: "Moda", status: "published", cover_image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=1200&q=80", featured: false, published_at: "2026-05-20T08:00:00.000Z", created_at: now, updated_at: now },
  { id: IDS[3], slug: "airbnb-mayor-expansion-transporte-experiencias-copa-mundial-2026", category: "Viajes", status: "published", cover_image: "https://images.unsplash.com/photo-1488646953014-85cb44e25828?auto=format&fit=crop&w=1200&q=80", featured: false, published_at: "2026-05-20T07:00:00.000Z", created_at: now, updated_at: now },
  { id: IDS[4], slug: "kitkat-alianza-global-formula-1-argentina", category: "Marcas", status: "published", cover_image: "https://site-762673.mozfiles.com/files/762673/medium/KITKAT_sponsor_global_de_Formula_1__1_.jpg", featured: false, published_at: "2026-05-20T06:00:00.000Z", created_at: now, updated_at: now },
  { id: IDS[5], slug: "puma-deviate-nitro-elite-4-showtime-running", category: "Deporte", status: "published", cover_image: "https://site-762673.mozfiles.com/files/762673/medium/044548_3.webp", featured: false, published_at: "2026-05-19T10:00:00.000Z", created_at: now, updated_at: now },
  { id: IDS[6], slug: "hublot-spirit-big-bang-essential-taupe-coleccion-2026", category: "Lujo", status: "published", cover_image: "https://images.unsplash.com/photo-1523170335258-f5ed11844a49?auto=format&fit=crop&w=1200&q=80", featured: false, published_at: "2026-05-14T10:00:00.000Z", created_at: now, updated_at: now },
  { id: IDS[7], slug: "air-supply-gran-rex-sold-out-50-aniversario", category: "Entretenimiento", status: "published", cover_image: "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?auto=format&fit=crop&w=1200&q=80", featured: false, published_at: "2026-05-14T09:00:00.000Z", created_at: now, updated_at: now },
  { id: IDS[8], slug: "bal-harbour-miami-mundial-fifa-2026", category: "Viajes", status: "published", cover_image: "https://cdn.uc.assets.prezly.com/7b4476fd-3bca-4819-aafd-3a0b4af3f426/-/resize/1120/-/format/auto/BH_Beach04-2022_21.JPG", featured: false, published_at: "2026-05-14T08:00:00.000Z", created_at: now, updated_at: now },
  { id: IDS[9], slug: "airbnb-estadio-monumental-gonzalo-montiel-experiencia", category: "Viajes", status: "published", cover_image: "https://images.unsplash.com/photo-1522778034537-20a2486be803?auto=format&fit=crop&w=1200&q=80", featured: false, published_at: "2026-05-14T07:00:00.000Z", created_at: now, updated_at: now },
  { id: IDS[10], slug: "honor-primera-tienda-argentina-abasto", category: "Tecnologia", status: "published", cover_image: "https://images.unsplash.com/photo-1491933382434-500287f9b54b?auto=format&fit=crop&w=1200&q=80", featured: false, published_at: "2026-05-10T10:00:00.000Z", created_at: now, updated_at: now },
  { id: IDS[11], slug: "epson-lifestudio-experiencia-inmersiva-san-telmo", category: "Tecnologia", status: "published", cover_image: "https://images.unsplash.com/photo-1593359677879-a4bb92f4834a?auto=format&fit=crop&w=1200&q=80", featured: false, published_at: "2026-05-07T10:00:00.000Z", created_at: now, updated_at: now },
  { id: IDS[12], slug: "vittoria-ceretti-met-gala-2026-carolina-herrera-wes-gordon", category: "Moda", status: "published", cover_image: "https://cdn.sender.net/email_images/172338/images/all/2026_05_04_vittoria_ceretti_custom_2026_met_gala.jpg", featured: false, published_at: "2026-05-07T09:00:00.000Z", created_at: now, updated_at: now },
  { id: IDS[13], slug: "mercedes-maybach-diablo-viste-moda-2-argentina", category: "Marcas", status: "published", cover_image: "https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=1200&q=80", featured: false, published_at: "2026-04-30T10:00:00.000Z", created_at: now, updated_at: now },
  { id: IDS[14], slug: "dibu-martinez-documental-netflix-mayo-2026", category: "Streaming", status: "published", cover_image: "https://images.unsplash.com/photo-1560272564-c83b66b1ad12?auto=format&fit=crop&w=1200&q=80", featured: true, published_at: "2026-04-30T09:00:00.000Z", created_at: now, updated_at: now },
  { id: IDS[15], slug: "oscar-2026-favoritos-chalamet-brasil-latin-america", category: "Entretenimiento", status: "published", cover_image: "https://images.unsplash.com/photo-1478720568477-152d9b164e26?auto=format&fit=crop&w=1200&q=80", featured: false, published_at: "2026-03-15T10:00:00.000Z", created_at: now, updated_at: now },
  { id: IDS[16], slug: "como-agua-para-chocolate-temporada-final-2026", category: "Streaming", status: "published", cover_image: "https://images.unsplash.com/photo-1484979045722-85e01c7f4783?auto=format&fit=crop&w=1200&q=80", featured: false, published_at: "2026-03-15T09:00:00.000Z", created_at: now, updated_at: now },
  { id: IDS[17], slug: "hublot-samuel-ross-colaboracion-big-bang-unico-sr-a-londres", category: "Lujo", status: "published", cover_image: "https://images.unsplash.com/photo-1550032568-61f3fc03f8d6?auto=format&fit=crop&w=1200&q=80", featured: false, published_at: "2026-03-06T10:00:00.000Z", created_at: now, updated_at: now },
];

const translations = [
  { post_id: IDS[0], locale: "es", title: "El mes de mayo en Palladio Hotel Buenos Aires celebra la identidad argentina con propuestas únicas", excerpt: "El hotel cinco estrellas de la colección MGallery programa gastronomía, vino y experiencias culturales para celebrar el patrimonio argentino durante mayo.", seo_title: null, seo_description: null, blocks: [{ id: bid(), type: "paragraph", text: "Palladio Hotel Buenos Aires es la propuesta del mes de mayo con una programación especial que honra la herencia argentina a través de la gastronomía, el vino y experiencias culturales. La propiedad de cinco estrellas de la colección MGallery combina hospitalidad de lujo con excelencia culinaria y narrativas históricas." }, { id: bid(), type: "heading", level: 2, text: "Propuestas del mes" }, { id: bid(), type: "paragraph", text: "El 25 de mayo, el Menú Patrio del Negresco Bistró ofrecerá tres platos especiales: empanadas de matambre con salsa criolla, locro clásico y turrón salteño de postre." }, { id: bid(), type: "paragraph", text: "El 28 de mayo, la Sala Rodríguez Peña recibe a Bodega El Esteco para una cata de vinos a las 19:30 h. El chef Facundo Stéfano diseñó un menú con maridajes que incluye humita y osobuco braseado, finalizando con tarta de chocolate patagónico. Costo: AR$ 50.000 por persona." }, { id: bid(), type: "paragraph", text: "El 30 de mayo, Sabores con Historia recorre las tradiciones porteñas de 1810 con un historiador y especialista en el museo del mate. Costo: AR$ 65.000 por persona." }, { id: bid(), type: "quote", text: "La cocina es la memoria de un pueblo.", byline: "Palladio Hotel Buenos Aires" }, { id: bid(), type: "paragraph", text: "Contacto: (+54 11) 3596 8870 | negresco@palladiohotel.com.ar | Av. Callao 924, Recoleta." }] },
  { post_id: IDS[1], locale: "es", title: "Récord de argentinos en Japón: del viaje imposible al destino que hoy todos quieren hacer", excerpt: "En 2025, 33.838 turistas argentinos visitaron Japón, superando el récord de 2019 y representando un aumento del 70% interanual. En tres décadas, el turismo argentino en Japón creció más del 740%.", seo_title: null, seo_description: null, blocks: [{ id: bid(), type: "paragraph", text: "En 2025, 33.838 turistas argentinos visitaron Japón, superando el récord anterior de 23.805 visitantes en 2019. Esto representa un aumento del 70% interanual frente a los 19.809 visitantes de 2024. En tres décadas, el turismo argentino en Japón creció más del 740%, desde aproximadamente 4.000 visitantes en 1995." }, { id: bid(), type: "heading", level: 2, text: "Accesibilidad económica" }, { id: bid(), type: "paragraph", text: "Japón se ha vuelto económicamente competitivo con los destinos europeos y norteamericanos. Los costos diarios incluyen ramen (USD 5-8), café (USD 2-3) y hoteles de negocios (USD 40-70 por noche). La depreciación del yen mejoró significativamente el poder adquisitivo de los turistas internacionales." }, { id: bid(), type: "heading", level: 2, text: "Factores culturales y sociales" }, { id: bid(), type: "paragraph", text: "La integración cultural —a través del anime, la gastronomía y el diseño— se ha profundizado. Las redes sociales amplifican el interés, con hashtags como #JapanTravel acumulando miles de millones de visualizaciones. El contenido ahora proviene de viajeros cotidianos, lo que hace que el destino se sienta aspiracional pero alcanzable." }, { id: bid(), type: "quote", text: "Los viajeros contemporáneos buscan experiencias auténticas más allá de los circuitos tradicionales.", byline: "David Esteban, CEO de Viajar por Asia" }] },
  { post_id: IDS[2], locale: "es", title: "Calvin Klein y Jung Kook reinterpretan los íconos de la marca con una nueva colaboración", excerpt: "La colección cápsula de 20 piezas reimagina los esenciales de Calvin Klein a través del estilo personal de Jung Kook, su primera colaboración de moda.", seo_title: null, seo_description: null, blocks: [{ id: bid(), type: "paragraph", text: "Calvin Klein anunció 'Jung Kook for Calvin Klein', una colección cápsula de edición limitada que marca la primera colaboración de moda del artista. Las 20 piezas reimaginan los esenciales icónicos de Calvin Klein a través de la estética personal de Jung Kook." }, { id: bid(), type: "heading", level: 2, text: "Detalles de la colección" }, { id: bid(), type: "paragraph", text: "La cápsula combina actitud biker con los códigos patrimoniales de Calvin Klein: ropa interior y siluetas denim clave, cazadoras trucker de los 90, cortes de pierna recta, low-rise baggy, camisetas gráficas, sudaderas y una chaqueta de carreras. El denim desgastado y las rayas de estilo racing completan la propuesta, con detalles personalizados incluidos logos personalizados, bordados ocultos y packaging exclusivo." }, { id: bid(), type: "heading", level: 2, text: "Dirección creativa" }, { id: bid(), type: "paragraph", text: "El director Alasdair McLellan dirigió una campaña cinematográfica que captura el espíritu rebelde de Jung Kook a través de imágenes inspiradas en motocicletas y retratos dinámicos." }, { id: bid(), type: "quote", text: "Esta cápsula se siente auténtica a mi estilo y a mi pasión por las motocicletas.", byline: "Jung Kook" }] },
  { post_id: IDS[3], locale: "es", title: "Airbnb anuncia su mayor expansión: transporte, compras, experiencias exclusivas de la Copa Mundial 2026 y hasta hoteles", excerpt: "Airbnb se expande más allá del alojamiento para convertirse en una plataforma de viajes integral, integrando servicios desde aeropuertos hasta restaurantes con estrellas Michelin.", seo_title: null, seo_description: null, blocks: [{ id: bid(), type: "paragraph", text: "Airbnb se expande significativamente más allá del alojamiento para convertirse en una plataforma de viajes integral. La empresa integra múltiples categorías de servicios para gestionar cada etapa de un viaje." }, { id: bid(), type: "heading", level: 2, text: "Nuevos servicios de viaje" }, { id: bid(), type: "paragraph", text: "Entre las novedades: reparto de comestibles en asociación con Instacart en más de 25 ciudades de EE. UU., traslados desde aeropuertos vía Welcome Pickups en más de 160 ciudades con descuentos del 20%, almacenamiento de equipaje a través de Bounce con descuentos del 15%, y alquiler de automóviles con incentivos del 20%." }, { id: bid(), type: "heading", level: 2, text: "Experiencias exclusivas del Mundial 2026" }, { id: bid(), type: "paragraph", text: "La expansión incluye miles de nuevas experiencias curadas: tours con expertos locales, más de 2.500 experiencias culinarias con colaboraciones de chefs con estrellas Michelin, y experiencias exclusivas de la Copa Mundial FIFA 2026 en seis ciudades sedes." }] },
  { post_id: IDS[4], locale: "es", title: "KitKat presenta en Argentina su alianza global con Fórmula 1", excerpt: "La icónica marca de Nestlé anunció su partnership global con la Fórmula 1 en Argentina, permitiéndole desarrollar campañas y experiencias centradas en el universo del automovilismo.", seo_title: null, seo_description: null, blocks: [{ id: bid(), type: "paragraph", text: "KitKat, la icónica marca de chocolate de Nestlé, anunció su partnership global con la Fórmula 1 en Argentina. La colaboración comenzó internacionalmente durante la temporada 2025 y ya inició sus primeras experiencias para el consumidor en el mercado local." }, { id: bid(), type: "paragraph", text: "La alianza permite a KitKat desarrollar campañas, contenidos y experiencias centradas en el universo de la Fórmula 1, reforzando su concepto fundacional de 'resignificar el valor de la pausa'." }, { id: bid(), type: "quote", text: "La pausa también es parte de la experiencia.", byline: "KitKat x Formula 1" }] },
  { post_id: IDS[5], locale: "es", title: "Steal the Show: PUMA presenta las nuevas Deviate NITRO™ Elite 4 SHOWTIME para running", excerpt: "PUMA presentó su última zapatilla de running competitiva, diseñada para atletas que buscan destacar en el día de carrera tanto en rendimiento como en diseño.", seo_title: null, seo_description: null, blocks: [{ id: bid(), type: "paragraph", text: "PUMA presentó su última zapatilla de running competitiva, la Deviate NITRO™ Elite 4 SHOWTIME, para atletas que buscan destacar el día de la carrera tanto en rendimiento como en diseño." }, { id: bid(), type: "heading", level: 2, text: "Diseño y rendimiento" }, { id: bid(), type: "paragraph", text: "La zapatilla presenta una llamativa paleta de colores que combina rosa neón, azul y amarillo, con amortiguación NITROFOAM™ ELITE de doble capa y placa de fibra de carbono PWRPLATE. Peso: 170 g. Altura de mediasuela: 40mm/32mm. Caída: 8mm." }] },
  { post_id: IDS[6], locale: "es", title: "Colección Essential, Capítulo 5: Hublot presenta el Spirit of Big Bang Essential Taupe", excerpt: "Hublot revela el quinto capítulo de su colección Essential, siguiendo una tradición anual para coleccionistas de relojes de todo el mundo. Un color, un diseño, una vez al año, exclusivamente online.", seo_title: null, seo_description: null, blocks: [{ id: bid(), type: "paragraph", text: "Hublot desvela el quinto capítulo de su colección Essential con el Spirit of Big Bang Essential Taupe. La marca mantiene su enfoque distintivo: un color, un diseño, una vez al año, disponible exclusivamente online." }, { id: bid(), type: "paragraph", text: "Limitado a 200 piezas por modelo. Versión 42mm: titanio con esfera de patrón carbono, movimiento cronógrafo HUB4700, reserva de marcha de 50 horas. Versión 32mm: acero inoxidable, movimiento automático HUB1120, reserva de 40 horas." }, { id: bid(), type: "quote", text: "Un color, un diseño, una vez al año.", byline: "Hublot" }] },
  { post_id: IDS[7], locale: "es", title: "Air Supply deslumbró en su primer Gran Rex sold out y se prepara para una segunda función", excerpt: "El legendario dúo británico-australiano actuó con lleno total en el Teatro Gran Rex de Buenos Aires como parte de su gira del 50 aniversario, reafirmando el vínculo histórico con el público argentino.", seo_title: null, seo_description: null, blocks: [{ id: bid(), type: "paragraph", text: "El legendario dúo Air Supply actuó con lleno total en el Teatro Gran Rex de Buenos Aires como parte de su gira del 50 Aniversario. Graham Russell y Russell Hitchcock interpretaron sus composiciones más célebres, con los fans cantando entusiastamente cada éxito clásico." }, { id: bid(), type: "quote", text: "Cincuenta años de música romántica que siguen emocionando igual que el primer día.", byline: "Air Supply en Argentina" }, { id: bid(), type: "paragraph", text: "Se programó una segunda función con lleno total el 13 de mayo de 2026. La banda ha vendido más de 20 millones de discos a nivel mundial." }] },
  { post_id: IDS[8], locale: "es", title: "Bal Harbour se convierte en la mejor opción para vivir el Mundial FIFA 2026 desde Miami", excerpt: "El municipio de lujo a 25 minutos del Hard Rock Stadium ofrece hoteles de playa, gastronomía exclusiva y playas tranquilas para los viajeros latinoamericanos.", seo_title: null, seo_description: null, blocks: [{ id: bid(), type: "paragraph", text: "Bal Harbour se posiciona como base ideal para vivir la Copa del Mundo 2026 desde Miami. El municipio acogerá siete partidos mundialistas en el Hard Rock Stadium, aproximadamente a 25 minutos en auto." }, { id: bid(), type: "paragraph", text: "Las opciones de alojamiento incluyen el St. Regis Bal Harbour Resort con suites frente al mar, el Sea View Hotel junto a la playa, y el Beach Haus Bal Harbour con suites familiares con cocina completa." }, { id: bid(), type: "quote", text: "Miami habla el idioma, come la comida y entiende el fútbol.", byline: "Bal Harbour Shops" }] },
  { post_id: IDS[9], locale: "es", title: "Dormir en el Monumental: el plan más exclusivo de Airbnb para vivir el fútbol desde adentro", excerpt: "Airbnb se asoció con Gonzalo Montiel para ofrecer acceso sin precedentes al Estadio Más Monumental: dos fanáticos podrán pasar la noche dentro del estadio más grande de Sudamérica.", seo_title: null, seo_description: null, blocks: [{ id: bid(), type: "paragraph", text: "Airbnb se asoció con el futbolista argentino Gonzalo Montiel para ofrecer acceso sin precedentes al Estadio Más Monumental. La plataforma ofrece dos experiencias distintas disponibles para reserva gratuita desde el 15 de mayo de 2026." }, { id: bid(), type: "paragraph", text: "Dos huéspedes se convertirán en los primeros fanáticos en dormir dentro del estadio, en un espacio privado dentro de un palco. La mañana incluye vistas al estadio y una degustación de mate tradicional. El único cupo disponible es del 29 al 30 de mayo de 2026." }, { id: bid(), type: "quote", text: "El 65% de las fechas de viaje más buscadas coinciden con eventos deportivos importantes.", byline: "Airbnb" }] },
  { post_id: IDS[10], locale: "es", title: "Así fue la apertura de la primera tienda de HONOR en Argentina", excerpt: "La marca tecnológica inauguró su primera Experience Zone en el Abasto Shopping con un evento que contó con Marley, Maxi López y Sofi Gonet, y un duelo tecnológico en vivo.", seo_title: null, seo_description: null, blocks: [{ id: bid(), type: "paragraph", text: "La marca tecnológica HONOR inauguró su primera Experience Zone en Argentina en el Abasto Shopping. El evento contó con Marley, Maxi López y Sofi Gonet como presentadores y convocó una gran asistencia pública durante la tarde." }, { id: bid(), type: "paragraph", text: "La pieza central fue el 'Duelo por el HONOR', con desafíos de fotografía, inteligencia artificial y pruebas de resistencia de smartphones. El evento cerró con DJ Pipo y sorteos de productos. La HONOR Experience Zone ya opera en el Abasto Shopping." }] },
  { post_id: IDS[11], locale: "es", title: "Epson llevó Lifestudio a una experiencia inmersiva en San Telmo", excerpt: "Epson presentó su nueva línea de proyectores inteligentes Lifestudio para entretenimiento en el hogar en un evento exclusivo en San Telmo con escenarios temáticos reales.", seo_title: null, seo_description: null, blocks: [{ id: bid(), type: "paragraph", text: "Epson presentó su nueva línea de proyectores inteligentes Lifestudio en un evento exclusivo en San Telmo. El venue contó con cuatro espacios temáticos: cine, gaming, música y reuniones sociales." }, { id: bid(), type: "paragraph", text: "El Lifestudio ofrece proyección de hasta 150 pulgadas, tecnología 3LCD con alta luminosidad, sistema de audio Bose integrado, ajuste automático de imagen y la app Epson Projection Studio™." }, { id: bid(), type: "quote", text: "Con Lifestudio buscamos redefinir cómo las personas viven el entretenimiento en el hogar.", byline: "Belén Terán, Senior Product Marketing Manager, Epson" }] },
  { post_id: IDS[12], locale: "es", title: "Vittoria Ceretti en la gala benéfica 2026 del Instituto del Traje del Met", excerpt: "La modelo lució un vestido de Carolina Herrera diseñado por Wes Gordon para la Met Gala 2026, inspirado en la escultura griega clásica con drapeado de seda negra.", seo_title: null, seo_description: null, blocks: [{ id: bid(), type: "paragraph", text: "La modelo Vittoria Ceretti lució un vestido personalizado de Carolina Herrera diseñado por el director creativo Wes Gordon en la Met Gala 2026. La propuesta exploró cómo la moda es arte, con foco en la estructura y el drapeado por sobre el ornamento." }, { id: bid(), type: "paragraph", text: "Gordon se inspiró en la escultura griega clásica: gasa de seda negra transparente, drapeado de alta costura que sigue las líneas naturales del cuerpo, sutil asimetría en el torso y falda alargada que extiende la silueta sin interrupciones." }, { id: bid(), type: "quote", text: "El cuerpo clásico dejó de ser algo idealizado para convertirse en algo natural.", byline: "Wes Gordon, director creativo de Carolina Herrera" }] },
  { post_id: IDS[13], locale: "es", title: "Mercedes-Maybach acompaña el estreno de El diablo se viste a la moda 2", excerpt: "El vehículo de lujo es el automóvil de Miranda Priestly en la secuela del icónico film de moda de 2006. La campaña 'The Art of Arrival' marca además el lanzamiento inaugural de Maybach en Argentina.", seo_title: null, seo_description: null, blocks: [{ id: bid(), type: "paragraph", text: "Mercedes-Maybach aseguró un destacado partnership con la secuela del icónico filme de moda de 2006, con el vehículo de lujo como el automóvil de Miranda Priestly (interpretada por Meryl Streep). La colaboración 'The Art of Arrival' enfatiza la presencia, el detalle y la experiencia a bordo." }, { id: bid(), type: "quote", text: "Maybach representa una expresión única de exclusividad, diseño y atención a cada detalle.", byline: "Martín Idiarte, Director Comercial de Prestige Auto" }, { id: bid(), type: "paragraph", text: "El timing del partnership coincide con el lanzamiento inaugural de Maybach en Argentina, marcando un hito histórico para la marca en el país." }] },
  { post_id: IDS[14], locale: "es", title: "Dibu Martínez: El pibe que ataja el tiempo — el documental de Netflix", excerpt: "Netflix anuncia un documental sobre el arquero argentino que estrena el 28 de mayo de 2026, combinando animaciones basadas en ilustraciones de Liniers, material de archivo personal y entrevistas con Messi y Scaloni.", seo_title: null, seo_description: null, blocks: [{ id: bid(), type: "paragraph", text: "Netflix anunció 'Dibu Martínez: El pibe que ataja el tiempo', que se estrena el 28 de mayo de 2026. Explora el recorrido del arquero desde Mar del Plata hasta convertirse en uno de los grandes héroes del fútbol." }, { id: bid(), type: "paragraph", text: "Producida por PEGSA (Agustín Pichot), basada en una historia de Hernán Casciari, dirigida por Gustavo Cova. Combina secuencias animadas basadas en ilustraciones de Liniers, archivo personal y entrevistas con Messi, Scaloni y el mentor 'Pepé' Santoro." }, { id: bid(), type: "quote", text: "Un pibe que descubre que tiene el poder de detener el tiempo.", byline: "Netflix" }] },
  { post_id: IDS[15], locale: "es", title: "Oscar 2026, los favoritos y por qué las declaraciones de Timothée Chalamet pueden influir", excerpt: "La 98ª edición de los Premios Oscar tiene a Brasil como principal representante latinoamericano, mientras las declaraciones de Chalamet modificaron las chances de los favoritos.", seo_title: null, seo_description: null, blocks: [{ id: bid(), type: "paragraph", text: "La 98ª ceremonia de los Premios Oscar destaca a Brasil como el principal representante de América Latina, luego de que Argentina no lograra obtener nominaciones. El filme 'El agente secreto', de Kleber Mendonça Filho, recibió cuatro nominaciones incluyendo Mejor Película y Mejor Actor para Wagner Moura." }, { id: bid(), type: "paragraph", text: "Timothée Chalamet recibió críticas tras declarar que no quería trabajar en ballet ni en ópera, afirmando que estas formas artísticas ya no importan culturalmente. Esta declaración modificó sus probabilidades de favorito a 2.20, detrás de Michael B. Jordan." }, { id: bid(), type: "quote", text: "Brasil asume el protagonismo latinoamericano tanto en el discurso cultural como en los mercados de apuestas para 2026.", byline: "PMag" }] },
  { post_id: IDS[16], locale: "es", title: "Como agua para chocolate entra en su etapa más decisiva con el episodio final", excerpt: "El quinto episodio de la temporada final explora el punto de inflexión emocional de la protagonista: culpa, miedo y amor chocan sin posibilidad de evasión en la hacienda que se vuelve más tensa que nunca.", seo_title: null, seo_description: null, blocks: [{ id: bid(), type: "paragraph", text: "El quinto episodio de la temporada final, 'Frijoles Gordos a la Tezcucana', se estrenó el 15 de marzo de 2026. La narrativa se intensifica cuando Tita confronta el conflicto entre sus verdaderos sentimientos y las expectativas familiares." }, { id: bid(), type: "paragraph", text: "Dirigida por Julián de Tavira, con guion de Silvia Ortega Vettoretti. Protagonizada por Irene Azuela y Azul Guaita. Producida para HBO/Warner Bros. Discovery. Episodio 6: 22 de marzo." }, { id: bid(), type: "quote", text: "La cocina se convierte en catalizador simbólico: el plato titular vehiculiza la revelación emocional.", byline: "PMag" }] },
  { post_id: IDS[17], locale: "es", title: "Hublot y el diseñador Samuel Ross celebran su nueva colaboración en Londres", excerpt: "El relojero suizo y Samuel Ross MBE presentaron el Big Bang Unico SR_A en un evento exclusivo en el rooftop CÉ LA VI London, con Tinie Tempah y otros referentes del mundo creativo.", seo_title: null, seo_description: null, blocks: [{ id: bid(), type: "paragraph", text: "Hublot y el diseñador Samuel Ross MBE organizaron un evento exclusivo en CÉ LA VI London, un restaurante en azotea dentro del Glass Cube de Renzo Piano, para presentar el 'Big Bang Unico SR_A' de edición limitada." }, { id: bid(), type: "paragraph", text: "La velada reunió a talentos del arte, la música y el cine, con Tinie Tempah y Lancey Foux entre los asistentes. DJ Skinny Macho amenizó la noche." }, { id: bid(), type: "quote", text: "Estructura, innovación de materiales y diseño industrial contemporáneo en un solo objeto.", byline: "Samuel Ross MBE" }] },
];

async function supabaseUpsert(table, rows) {
  const res = await fetch(`${SUPABASE_URL}/rest/v1/${table}`, {
    method: "POST",
    headers: { ...headers, Prefer: "resolution=merge-duplicates,return=minimal" },
    body: JSON.stringify(rows),
  });
  if (!res.ok) {
    const body = await res.text();
    throw new Error(`${table} upsert failed (${res.status}): ${body}`);
  }
}

async function main() {
  console.log("Seeding posts...");
  await supabaseUpsert("posts", posts);
  console.log(`  ✓ ${posts.length} posts upserted`);

  console.log("Seeding translations...");
  // Delete existing translations first to avoid duplicates on re-run
  for (const id of IDS) {
    await fetch(`${SUPABASE_URL}/rest/v1/post_translations?post_id=eq.${id}`, {
      method: "DELETE",
      headers,
    });
  }
  await supabaseUpsert("post_translations", translations);
  console.log(`  ✓ ${translations.length} translations upserted`);

  console.log("\nDone! Verifying...");
  const res = await fetch(`${SUPABASE_URL}/rest/v1/posts?select=slug,status&order=published_at.desc`, {
    headers: { apikey: SERVICE_KEY, Authorization: `Bearer ${SERVICE_KEY}` },
  });
  const rows = await res.json();
  console.log(`  ${rows.length} posts in DB:`);
  rows.forEach(r => console.log(`    - [${r.status}] ${r.slug}`));
}

main().catch(err => { console.error(err); process.exit(1); });
